"""Intermediate representation for AI-generated BFMs.

The IR records source artifacts, semantic interface roles, and concrete DUT
paths. It intentionally does not encode a built-in bus protocol. Protocol
behavior is expected to be generated by an agent from the IR and source files.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


class IRValidationError(ValueError):
    """Raised when an IR document is internally inconsistent."""


def _require(mapping: dict[str, Any], key: str, where: str) -> Any:
    if key not in mapping:
        raise IRValidationError(f"missing required key {where}.{key}")
    return mapping[key]


def _as_int(value: Any, where: str) -> int:
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        return int(value, 0)
    raise IRValidationError(f"{where} must be an integer or integer string")


@dataclass(frozen=True)
class SignalBindingIR:
    """Binding from a semantic signal name to a concrete DUT path."""

    name: str
    role: str
    hdl_path: str
    width: int | None = None
    direction: str | None = None
    active: str | None = None
    required: bool = True
    confidence: float | None = None
    source: str | None = None
    aliases: tuple[str, ...] = ()

    @classmethod
    def from_dict(cls, name: str, data: dict[str, Any]) -> "SignalBindingIR":
        role = str(_require(data, "role", f"bindings.{name}"))
        hdl_path = str(_require(data, "hdl_path", f"bindings.{name}"))
        width = data.get("width")
        if width is not None:
            width = _as_int(width, f"bindings.{name}.width")
        aliases = tuple(str(alias) for alias in data.get("aliases", ()))
        return cls(
            name=name,
            role=role,
            hdl_path=hdl_path,
            width=width,
            direction=data.get("direction"),
            active=data.get("active"),
            required=bool(data.get("required", True)),
            confidence=data.get("confidence"),
            source=data.get("source"),
            aliases=aliases,
        )


@dataclass(frozen=True)
class SourceArtifactIR:
    """A file or document used by the agent to infer BFM behavior."""

    path: str
    kind: str
    role: str | None = None
    description: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SourceArtifactIR":
        return cls(
            path=str(_require(data, "path", "sources[]")),
            kind=str(_require(data, "kind", "sources[]")),
            role=data.get("role"),
            description=data.get("description"),
            metadata=dict(data.get("metadata", {})),
        )


@dataclass(frozen=True)
class InterfaceIR:
    """A semantic interface with role-to-binding references.

    `protocol` is a label inferred by the agent or provided by the user. This
    framework stores it but does not validate protocol-specific signal roles.
    """

    name: str
    protocol: str | None
    signals: dict[str, str]
    clock: str | None = None
    reset: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, name: str, data: dict[str, Any]) -> "InterfaceIR":
        signals = {
            str(role): str(binding_name)
            for role, binding_name in _require(
                data, "signals", f"interfaces.{name}"
            ).items()
        }
        return cls(
            name=name,
            protocol=(
                str(data.get("type", data.get("protocol")))
                if data.get("type", data.get("protocol")) is not None
                else None
            ),
            signals=signals,
            clock=str(data["clock"]) if "clock" in data else None,
            reset=str(data["reset"]) if "reset" in data else None,
            metadata=dict(data.get("metadata", {})),
        )

    def validate(self, bindings: dict[str, SignalBindingIR]) -> None:
        referenced = [*self.signals.values()]
        if self.clock is not None:
            referenced.append(self.clock)
        if self.reset is not None:
            referenced.append(self.reset)
        for binding_name in referenced:
            if binding_name not in bindings:
                raise IRValidationError(
                    f"interface {self.name} references unknown binding {binding_name}"
                )


@dataclass(frozen=True)
class FieldIR:
    """A field inside a register."""

    name: str
    lsb: int
    width: int
    access: str = "rw"

    @classmethod
    def from_dict(cls, name: str, data: dict[str, Any]) -> "FieldIR":
        return cls(
            name=name,
            lsb=_as_int(_require(data, "lsb", f"fields.{name}"), f"fields.{name}.lsb"),
            width=_as_int(
                _require(data, "width", f"fields.{name}"), f"fields.{name}.width"
            ),
            access=str(data.get("access", "rw")).lower(),
        )

    @property
    def mask(self) -> int:
        return ((1 << self.width) - 1) << self.lsb

    def extract(self, value: int) -> int:
        return (value & self.mask) >> self.lsb

    def insert(self, register_value: int, field_value: int) -> int:
        max_value = (1 << self.width) - 1
        if field_value < 0 or field_value > max_value:
            raise ValueError(
                f"field {self.name} value {field_value} does not fit in {self.width} bits"
            )
        cleared = register_value & ~self.mask
        return cleared | ((field_value << self.lsb) & self.mask)


@dataclass(frozen=True)
class RegisterIR:
    """Register address and field layout."""

    name: str
    offset: int
    fields: dict[str, FieldIR]
    access: str = "rw"
    width: int | None = None

    @classmethod
    def from_dict(cls, name: str, data: dict[str, Any]) -> "RegisterIR":
        fields = {
            str(field_name): FieldIR.from_dict(str(field_name), field_data)
            for field_name, field_data in data.get("fields", {}).items()
        }
        return cls(
            name=name,
            offset=_as_int(
                _require(data, "offset", f"registers.{name}"),
                f"registers.{name}.offset",
            ),
            fields=fields,
            access=str(data.get("access", "rw")).lower(),
            width=(
                _as_int(data["width"], f"registers.{name}.width")
                if "width" in data
                else None
            ),
        )

    def decode(self, value: int) -> dict[str, int]:
        return {
            field_name: field.extract(value)
            for field_name, field in self.fields.items()
        }

    def encode(self, field_values: dict[str, int], base_value: int = 0) -> int:
        value = base_value
        for field_name, field_value in field_values.items():
            if field_name not in self.fields:
                raise KeyError(f"unknown field {self.name}.{field_name}")
            value = self.fields[field_name].insert(value, field_value)
        return value


@dataclass(frozen=True)
class DesignIR:
    """Top-level IR consumed by generators and runtime BFMs."""

    top: str
    interfaces: dict[str, InterfaceIR]
    bindings: dict[str, SignalBindingIR]
    sources: tuple[SourceArtifactIR, ...] = ()
    registers: dict[str, RegisterIR] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DesignIR":
        design = _require(data, "design", "ir")
        top = str(_require(design, "top", "design"))
        bindings = {
            str(name): SignalBindingIR.from_dict(str(name), binding_data)
            for name, binding_data in _require(data, "bindings", "ir").items()
        }
        interfaces = {
            str(name): InterfaceIR.from_dict(str(name), iface_data)
            for name, iface_data in _require(data, "interfaces", "ir").items()
        }
        sources = tuple(
            SourceArtifactIR.from_dict(source_data)
            for source_data in data.get("sources", ())
        )
        registers = {
            str(name): RegisterIR.from_dict(str(name), reg_data)
            for name, reg_data in data.get("registers", {}).items()
        }
        ir = cls(
            top=top,
            interfaces=interfaces,
            bindings=bindings,
            sources=sources,
            registers=registers,
            metadata=dict(data.get("metadata", {})),
        )
        ir.validate()
        return ir

    def validate(self) -> None:
        if not self.interfaces:
            raise IRValidationError("IR must define at least one interface")
        for interface in self.interfaces.values():
            interface.validate(self.bindings)

    def register_by_offset(self, offset: int) -> RegisterIR | None:
        for register in self.registers.values():
            if register.offset == offset:
                return register
        return None
